### ISSUE TITLE
What's the best way to load bats-assert

### ISSUE THREAD

**Issue by jizusun** [ffurrer2/docker-bats#2]
Thank you so much for the docker image!

I found the Dockerfile includes `bats-asserts`
https://github.com/ffurrer2/docker-bats/blob/98a5ab67a6029368bbe40d4eb1d6ae251f85a79e/Dockerfile#L39-L43
But how can I load them in my `setup`?

Best regards,
Jizu

**Comment by ffurrer2** [comment]
Hi Jizu,

you can use the [load](https://github.com/sstephenson/bats#load-share-common-code) command from bats in your `.bats` file:

```sh
load '/opt/bats-assert/load.bash'
```

Here can you find a complete example: https://github.com/ffurrer2/extract-release-notes/blob/d3e0ee8b1d3eabe5362c857cae268b5e078a8861/test/bats/test_docker_container.bats

Best regards,
Felix
